site_name: Open Science Guidebook for Neuroscientists
theme:
  name: material
  logo: assets/logos/enigma_300DPI_small.png
  favicon: assets/logos/enigma_300DPI_small.png
  palette:
    primary: amber
  

features:
  - navigation.indexes

nav:
  - Welcome: docs/index.md

  - Chapters:    
    - Introduction: docs/tabs/1-introduction.md
    - Preregistration & Protocols: docs/tabs/2-preregistration_protocols.md
    - Data Organisation: docs/tabs/3-data_organisation.md
    - Open Software & Tools: docs/tabs/4-open_software_tools.md
    - Publishing & Preprints: docs/tabs/5-publishing_preprints.md
    - Communication: docs/tabs/6-communication.md
    - Create Your Own Open Science Working Group: docs/tabs/7-create_open_science_working_group.md
    - Recognition & Reward: docs/tabs/8-recognition_reward.md
    - Open Science in Education: docs/tabs/9-educational_resources.md
    
  - About the team: /docs/working_group/team.md
  
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
