site_name: Open Science Guidebook for Neuroscientists
theme:
  name: material
  logo: assets/logos/enigma_300DPI_small.png
  favicon: assets/logos/enigma_300DPI_small.png
  palette:
    primary: teal
  

features:
  - navigation.indexes

nav:
  - Welcome: index.md

  - Chapters:    
    - Introduction: tabs/1-introduction.md
    - Preregistration & Protocols: tabs/2-preregistration_protocols.md
    - Data Organisation: tabs/3-data_organisation.md
    - Open Software & Tools: tabs/4-open_software_tools.md
    - Publishing & Preprints: tabs/5-publishing_preprints.md
    - Communication: tabs/6-communication.md
    - Create Your Own Open Science Working Group: tabs/7-create_open_science_working_group.md
    - Recognition & Reward: tabs/8-recognition_reward.md
    - Open Science in Education: tabs/9-educational_resources.md
    
  - About the team: working_group/team.md
  
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
