site_name: Open Science Guidebook for Neuroscientists
theme:
  name: material
  logo: assets/logos/Logo_OS_Guidebook_better_readability.png
  favicon: assets/logos/Logo_OS_Guidebook_better_readability.png
  palette:
    primary: deep purple
  

features:
  - navigation.indexes

nav:
  - Welcome: index.md

  - Chapters:    
    - 1. Introduction: tabs/1-introduction.md
    - 2. Preregistration & Protocols: tabs/2-preregistration_protocols.md
    - 3. Data Organisation: tabs/3-data_organisation.md
    - 4. Open Software & Tools: tabs/4-open_software_tools.md
    - 5. Publishing & Preprints: tabs/5-publishing_preprints.md
    - 6. Science Communication: tabs/6-communication.md
    - 7. Set up Your Own Working Group: tabs/7-create_open_science_working_group.md
    - 8. Recognition & Reward: tabs/8-recognition_reward.md
    
  - About the team: working_group/core_team.md

  - Amsterdam UMC Open Science Awards: awards/aumc_awards.md
  
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css
